font_family      Fira Code
font_size        11
bold_font        Fira Code Bold
italic_font      Fira Code Italic

shell fish

scrollback_indicator_opacity 0
confirm_os_window_close 0
background_opacity 0.7

tab_bar_style powerline
tab_powerline_style round

include current-theme.conf
